FROM nginx:alpine

# RUN chown -R nginx:nginx /var/www/templates
# Set working directory
WORKDIR /var/www
COPY ./src/ /var/www/

RUN chown -R 101:101 /var/www/templates
# RUN chown -R 101:101 /var/www/react-app

